name: Check server-side rendering
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  deployment_status:
jobs:
  check-ssr:
    runs-on: ubuntu-latest
    steps:
      - name: Skip SSR check
        if: github.event_name != 'deployment_status' || github.event.deployment_status.state != 'success'
        run: echo "Waiting for deployment to complete"
      - name: Check if node/6 is ssr rendered
        if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
        run: |
          URL=$(echo ${{ github.event.deployment_status.environment_url }})/node/6
          echo "Fetch the URL: $URL"
          curl -s $URL | grep -q "Originally Detonátor route (this message used for SSR check)"
          if [ $? -eq 0 ]; then
              echo "Server-side rendering is working"
          else
              echo "Server-side rendering broken"
              exit 1
          fi

